name: Go Matrix
on:
 push:
  branches:
      - prod
      - staging
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [prod, staging, develop] #Array of org mnemonics to use below
        include:
          # includes a new variable for each org (this is effectively a switch statement) 
         - org: prod
           username: PROD_USERNAME
           runtime: prod  
         - org: staging
           username: STAGING_USERNAME
           runtime:  staging
         - org: develop
           username: DEVELOP_USERNAME
           runtime: develop 
    
    steps:
      - name: Print secret
        if: endsWith(github.event.ref, matrix.runtime)
        run: |
          echo ${{ secrets[matrix.username] }};
          echo ${{ matrix.runtime }};
          echo ${{ toJson(matrix) }};
          

