name: Go Matrix
on:
 push:
  branches:
      - prod
      - staging
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [prod, staging, develop] #Array of org mnemonics to use below
        include:
          # includes a new variable for each org (this is effectively a switch statement) 
         - org: prod
           username: PROD_USERNAME
           branch: prod  
         - org: staging
           username: STAGING_USERNAME
           branch:  staging
         - org: develop
           username: DEVELOP_USERNAME
           branch: develop 
    
    steps:
      - name: Print secret
        if: endsWith(github.event.ref, matrix.branch)
        run: |
          echo ${{ secrets[matrix.username] }};
         
  setenv:
   name: SetEnv
   runs-on: ubuntu-latest
   steps:
     - name: Set Environment
       run: echo "::set-env name=USERNAME::${GITHUB_REF##*/}_USERNAME"    
     - name: Print Secret
       run: echo ${{ secrets[steps.username] }};
